# Generated by Django 2.2.9 on 2020-02-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0010_auto_20200220_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_id2',
            field=models.CharField(default='', max_length=100),
        ),
    ]
