# Generated by Django 2.2.9 on 2020-02-21 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saler', '0011_product_product_id2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productsize',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
